// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlacementCellBackend.Data;
using PlacementCellBackend.Models.InterviewRounds;

#nullable disable

namespace PlacementCellBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110100000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlacementCellBackend.Models.Alumni", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Linkdinprofile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("alumni");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.AlumniFeedBackonCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CTC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkMode")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("alumnifeedbackoncompany");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.AlumniJobPostion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostedId")
                        .HasColumnType("text");

                    b.Property<string>("PostedByEmployeeId")
                        .HasColumnType("text");

                    b.Property<int>("PostedBytype")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("Date");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PostedId");

                    b.HasIndex("PostedByEmployeeId");

                    b.ToTable("alumnijobposition");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Companyemployee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("companyemployee");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.EmployeeFeedbackonStudent", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordId"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmpId")
                        .HasColumnType("text");

                    b.Property<string>("CompnayEmpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.HasIndex("CompanyEmpId");

                    b.ToTable("employeefeedbackonstudent");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.ExperienceOpening", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("companyempEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("experiencerequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("jobid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("experienceopening");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.FoodReview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id");

                    b.ToTable("foodReview");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Placement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PlacementDate")
                        .HasColumnType("Date");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id");

                    b.ToTable("placement");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Restaurents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("restaurents");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GraduationYear")
                        .HasColumnType("bigint");

                    b.Property<string>("major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("teacher");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.TeacherResearchOpening", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly?>("DeadLine")
                        .HasColumnType("Date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("Date");

                    b.Property<string>("Researcharea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stipend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Id");

                    b.ToTable("teacherresearchopening");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Alumni", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.AlumniFeedBackonCompany", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Alumni", "Alumni")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PlacementCellBackend.Models.InterviewRounds.CodingRound", "CodingRoundInfo", b1 =>
                        {
                            b1.Property<string>("AlumniFeedBackonCompanyId")
                                .HasColumnType("text");

                            b1.Property<string>("CodingPlatform")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("DifficultyLevel")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("Duration")
                                .HasColumnType("time without time zone");

                            b1.Property<int>("InterviewMode")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<List<string>>("Questions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("CodingRoundInfo_Questions");

                            b1.HasKey("AlumniFeedBackonCompanyId");

                            b1.ToTable("alumnifeedbackoncompany");

                            b1.WithOwner()
                                .HasForeignKey("AlumniFeedBackonCompanyId");
                        });

                    b.OwnsOne("PlacementCellBackend.Models.InterviewRounds.HRRound", "HRRoundInfo", b1 =>
                        {
                            b1.Property<string>("AlumniFeedBackonCompanyId")
                                .HasColumnType("text");

                            b1.Property<string>("InterviewDuration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("InterviewMode")
                                .HasColumnType("integer");

                            b1.Property<List<SituationBasedQuestion>>("SituationBasedQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("HRRoundInfo_SituationBasedQuestions");

                            b1.Property<List<UnExpectedQuestion>>("UnExpectedQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("HRRoundInfo_UnExpectedQuestions");

                            b1.HasKey("AlumniFeedBackonCompanyId");

                            b1.ToTable("alumnifeedbackoncompany");

                            b1.WithOwner()
                                .HasForeignKey("AlumniFeedBackonCompanyId");
                        });

                    b.OwnsOne("PlacementCellBackend.Models.InterviewRounds.Resources", "ResourcesInfo", b1 =>
                        {
                            b1.Property<string>("AlumniFeedBackonCompanyId")
                                .HasColumnType("text");

                            b1.Property<List<BookResource>>("Books")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("ResourcesInfo_Books");

                            b1.Property<List<LinkResource>>("Links")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("ResourcesInfo_Links");

                            b1.HasKey("AlumniFeedBackonCompanyId");

                            b1.ToTable("alumnifeedbackoncompany");

                            b1.WithOwner()
                                .HasForeignKey("AlumniFeedBackonCompanyId");
                        });

                    b.OwnsOne("PlacementCellBackend.Models.InterviewRounds.TechnicalRound", "TechnicalRoundInfo", b1 =>
                        {
                            b1.Property<string>("AlumniFeedBackonCompanyId")
                                .HasColumnType("text");

                            b1.Property<List<CoreCSQuestion>>("CoreCSQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("TechnicalRoundInfo_CoreCSQuestions");

                            b1.Property<List<DSAQuestion>>("DSAQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("TechnicalRoundInfo_DSAQuestions");

                            b1.Property<string>("InterviewDuration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("InterviewMode")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<List<ValueTuple<string, ValueTuple<string, string>>>>("PuzzleBasedQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("TechnicalRoundInfo_PuzzleBasedQuestions");

                            b1.PrimitiveCollection<List<ValueTuple<string, ValueTuple<string, string>>>>("SystemDesignQuestions")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("TechnicalRoundInfo_SystemDesignQuestions");

                            b1.HasKey("AlumniFeedBackonCompanyId");

                            b1.ToTable("alumnifeedbackoncompany");

                            b1.WithOwner()
                                .HasForeignKey("AlumniFeedBackonCompanyId");
                        });

                    b.Navigation("Alumni");

                    b.Navigation("CodingRoundInfo");

                    b.Navigation("Company");

                    b.Navigation("HRRoundInfo");

                    b.Navigation("ResourcesInfo");

                    b.Navigation("TechnicalRoundInfo");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.AlumniJobPostion", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlacementCellBackend.Models.Alumni", "PostedByAlumni")
                        .WithMany()
                        .HasForeignKey("PostedId");

                    b.HasOne("PlacementCellBackend.Models.Companyemployee", "PostedByEmployee")
                        .WithMany()
                        .HasForeignKey("PostedByEmployeeId");

                    b.Navigation("Company");

                    b.Navigation("PostedByAlumni");

                    b.Navigation("PostedByEmployee");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Companyemployee", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.EmployeeFeedbackonStudent", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Companyemployee", "CompanyEmployee")
                        .WithMany()
                        .HasForeignKey("CompanyEmpId");

                    b.Navigation("CompanyEmployee");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.ExperienceOpening", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.FoodReview", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlacementCellBackend.Models.Restaurents", "Restaurent")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Restaurent");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.Placement", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlacementCellBackend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PlacementCellBackend.Models.TeacherResearchOpening", b =>
                {
                    b.HasOne("PlacementCellBackend.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}

