spring.application.name=PlacementicsBackend

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.lwmqlkvzwuwrojazmepj&sslmode=require
spring.datasource.username=postgres.lwmqlkvzwuwrojazmepj
spring.datasource.password=IIITDMK

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.sender-name=PlacementCell

google.calendar.service-account-key-path=
google.calendar.application-name=PlacementCell MentorMentee
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
