spring.application.name=PlacementicsBackend

spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.sender-name=PlacementCell

app.cors.allowed-origins=http://localhost:3000

google.calendar.service-account-key-path=
google.calendar.application-name=PlacementCell MentorMentee

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.example.placementicsbackend.controllers
